### ISSUE TITLE
Text not appearing in Captcha

### ISSUE THREAD

**Issue by KuwuNekoshi** [Shashank3736/captcha-canvas#54]
I'm having some issues making the text appear in the captcha, running it on my local machine works fine, but running it on our host(railway.app) it doesn't add the text to the image.
We have tried a few different solutions from previous questions, but none of them seemed to solve our issues..

Local (works as expected)
![image](https://i.gyazo.com/b5cdfa596e63cef0c62b472056035046.png)

Host (Doesn't add text)
![image](https://i.gyazo.com/c2cab40de26bc6432d28bdcd23064bad.png)

We're running it in docker (on host only):
![image](https://i.gyazo.com/07fd5e782c244379aa4cfd5e869c3673.png)

And we have our dependencies in package:
![image](https://user-images.githubusercontent.com/109879062/222887652-6c4f1ba1-9aa4-46e7-97a2-d642622f96e6.png)

The code:
![image](https://i.gyazo.com/7a9dbc2919f5d8c69abd6f7415efbf2d.png)

**Comment by Shashank3736** [comment]
Do you mind trying `v2.3.1` because maybe the issue is with `skia-canvas`. `skia-canvas` has made some breaking changes recently which is affecting the package alot. I m planning to restart my work on `v2.4.0` so i can provide the same level of customization using `canvas` module.
```
npm i captcha-canvas@2.3.1
```

Link to docs for v2: https://captcha-canvas.js.org/v2/index.html

--- 
As far as I remember your current configuration should work fine with the `v2.3.1`.

**Comment by KuwuNekoshi** [comment]
Changing to v2.3.1 and switching from alpine to bullseye worked out!
Thank you very much 😄
